// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ddU6vWqhI_o0nMPmjxqn2hNisc2Hw-A',
    appId: '1:87612941039:web:0e8d1bd9be73013dccb11a',
    messagingSenderId: '87612941039',
    projectId: 'test-app-df785',
    authDomain: 'test-app-df785.firebaseapp.com',
    storageBucket: 'test-app-df785.firebasestorage.app',
    measurementId: 'G-KL78D505B0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1MEgkwi-kXOoNQ794DgdL8yViUSlpZug',
    appId: '1:87612941039:android:f49e185d0b2036aaccb11a',
    messagingSenderId: '87612941039',
    projectId: 'test-app-df785',
    storageBucket: 'test-app-df785.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsIUGpbQ_XDXwMBJkqIdNWliNMRTJR8YQ',
    appId: '1:87612941039:ios:51ddde10812f4e24ccb11a',
    messagingSenderId: '87612941039',
    projectId: 'test-app-df785',
    storageBucket: 'test-app-df785.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsIUGpbQ_XDXwMBJkqIdNWliNMRTJR8YQ',
    appId: '1:87612941039:ios:51ddde10812f4e24ccb11a',
    messagingSenderId: '87612941039',
    projectId: 'test-app-df785',
    storageBucket: 'test-app-df785.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7ddU6vWqhI_o0nMPmjxqn2hNisc2Hw-A',
    appId: '1:87612941039:web:4af1a705771c710bccb11a',
    messagingSenderId: '87612941039',
    projectId: 'test-app-df785',
    authDomain: 'test-app-df785.firebaseapp.com',
    storageBucket: 'test-app-df785.firebasestorage.app',
    measurementId: 'G-SWH5LV3R6G',
  );
}
